@startuml
hide empty description

[*] --> 利用主体

state 利用主体 <<choice>>

利用主体 --> 弊行口座開設者
利用主体 --> 新規口座開設者
利用主体 --> 外部利用者

新規口座開設者 --> 新規口座開設
弊行口座開設者 --> 認証
外部利用者 --> 外部利用者メニュー

state 新規口座開設 {
    [*] --> 口座情報入力待ち

    口座情報入力待ち --> 口座開設処理実行 : 口座情報入力完了
    口座開設処理実行 --> 口座開設完了 : 口座開設処理完了
    口座開設完了 --> [*]
}

新規口座開設 --> [*]

state 認証 {
    [*] --> カード挿入待ち

    カード挿入待ち --> PIN入力待ち : カード挿入
    PIN入力待ち --> 認証成功 : 正しいPIN入力
    PIN入力待ち --> 認証失敗 : 間違ったPIN入力

    認証失敗 --> カード挿入待ち : 再試行
}

認証成功 --> 口座開設者メニュー : 認証成功

state 口座開設者メニュー {
    [*] --> 現金預入
    [*] --> 現金引出
    [*] --> 振込送金
}

state 現金預入 {
    [*] --> 入金待ち

    入金待ち --> 預入実行 : 金額入力完了
    預入実行 --> 口座開設者メニュー : 預入処理完了
}

state 現金引出 {
    [*] --> 金額入力待ち

    金額入力待ち --> 引出実行 : 金額入力完了
    引出実行 --> 口座開設者メニュー : 引出処理完了
}

state 振込送金 {
    [*] --> 振込情報入力待ち

    振込情報入力待ち --> 振込内容確認 : 振込情報入力完了
    振込内容確認 --> 振込実行 : 確認OK
    振込内容確認 --> 振込情報入力待ち : 修正

    振込実行 --> 口座開設者メニュー : 振込処理完了
}

口座開設者メニュー --> [*]

state 外部利用者メニュー {
    [*] --> 振込入金
    [*] --> 払込入金

    振込入金 --> 外部利用者メニュー
    払込入金 --> 外部利用者メニュー
}

state 振込入金 {
    [*] --> 振込情報送信待ち

    振込情報送信待ち --> 振込入金処理実行 : 振込情報受信
    振込入金処理実行 --> 振込入金 : 処理完了
}

state 払込入金 {
    [*] --> 払込情報送信待ち

    払込情報送信待ち --> 払込入金処理実行 : 払込情報受信
    払込入金処理実行 --> 払込入金 : 処理完了
}

外部利用者メニュー --> [*]

@enduml
