@startuml

actor "弊行口座開設顧客"
rectangle "銀行" {
    弊行口座開設顧客 --> (現金預入)
    弊行口座開設顧客 --> (現金引出)
    弊行口座開設顧客 --> (自他行口座へ振込送金)
}

actor "他行口座開設者"
rectangle "銀行" {
    他行口座開設者 --> (弊行口座へ振込送金)
}

actor "払込利用者"
rectangle "銀行" {
    払込利用者 --> (弊行口座への払込)
}

@enduml
