@startuml title 問題の状態遷移図
[*] --> q_0: <math>(x_1, x_2) = (0, 0)</math>

' 0円
q_0: 0
q_0 --> q_0: <math>(0, 0)</math>
q_0 --> q_1: <math>(1, 0)</math>
q_0 --> q_5: <math>(0, 1)</math>

' 10円
q_1: 0
q_1 -> q_1: <math>(0, 0)</math>
q_1 --> q_2: <math>(1, 0)</math>
q_1 --> q_prime_0: <math>(0, 1)</math>

' 20円
q_2: 0
q_2 --> q_2: <math>(0, 0)</math>
q_2 --> q_3: <math>(1, 0)</math>
q_2 --> q_prime_1: <math>(0, 1)</math>

' 30円
q_3: 0
q_3 --> q_3: <math>(0, 0)</math>
q_3 --> q_4: <math>(1, 0)</math>
q_3 --> q_prime_2: <math>(0, 1)</math>

' 40円
q_4: 0
q_4 --> q_4: <math>(0, 0)</math>
q_4 --> q_5: <math>(1, 0)</math>
q_4 --> q_prime_3: <math>(0, 1)</math>

' 50円
q_5: 0
q_5 --> q_5: <math>(0, 0)</math>
q_5 --> q_prime_0: <math>(1, 0)</math>
q_5 --> q_prime_4: <math>(0, 1)</math>

' 60円
q_prime_0: 1
q_prime_0 --> q_0: <math>(0, 0)</math>
q_prime_0 --> q_1: <math>(1, 0)</math>
q_prime_0 --> q_5: <math>(0, 1)</math>

' 70円
q_prime_1: 1
q_prime_1 --> q_1: <math>(0, 0)</math>
q_prime_1 --> q_2: <math>(1, 0)</math>
q_prime_1 --> q_prime_0: <math>(0, 1)</math>

' 80円
q_prime_2: 1
q_prime_2 --> q_2: <math>(0, 0)</math>
q_prime_2 --> q_3: <math>(1, 0)</math>
q_prime_2 --> q_prime_1: <math>(0, 1)</math>

' 90円
q_prime_3: 1
q_prime_3 --> q_3: <math>(0, 0)</math>
q_prime_3 --> q_4: <math>(1, 0)</math>
q_prime_3 --> q_prime_2: <math>(0, 1)</math>

' 100円
q_prime_4: 1
q_prime_4 --> q_4: <math>(0, 0)</math>
q_prime_4 --> q_5: <math>(1, 0)</math>
q_prime_4 --> q_prime_3: <math>(0, 1)</math>
@enduml
