name: Attach Compile Artifacts

on:
  pull_request:

jobs:
  typst-compile-attach:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Install fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-cjk-extra ttf-mscorefonts-installer

      - name: Set up Typst
        uses: typst-community/setup-typst@f5c90506c7ae74fca20e339034af05c52e0eda92 # v3.1.0

      - name: Compile Typst files
        run: |
          typst compile "**/*.typ"

      - name: Upload compiled PDFs
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: compiled-pdfs

      - name: Attach PDFs to PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@ff15f0306b3f739f7b6fd43fb5d26cd321bd4de5 # v3.2.1
        with:
          name: compiled-pdfs
